environment:
  matrix:
    - nodejs_version: '12'
install:
  - ps: Install-Product node $env:nodejs_version
  - yarn
before_test:
  - SET PGUSER=postgres
  - SET PGPASSWORD=Password12!
  - PATH=C:\Program Files\PostgreSQL\10\bin\;%PATH%
  - createdb testdb
test_script:
  - node --version
  - yarn test
services:
  - postgresql101
build: off
